### PR TITLE
Add public ability to get function name

### PR DESCRIPTION
**Pull request by illicitonion**

### CODE REVIEW

**Comment by damienmg** [comment]
Thanks Daniel for your contributions. I am missing context on what this function is for? Do you care to elaborate a bit on the purpose of this change?

**Comment by illicitonion** [comment]
Of course, sorry for not doing so already!

I have prototyped using starlark-rust for BUILD file parsing in Pants, and the first cut does so by registering Starlark functions for each Python function that may appear in a BUILD file, and tracking calls.

In a handful of cases, pants BUILD files may use functions as values - imagine:
```python
python_library(
  name = "foo",
  function_to_apply_to_sources=add_trailing_newline,
)
```

where `add_trailing_newline` is a python-implemented function which Pants knows about.

Starlark needs to be able to pass this reference to the function back up to Python, for it to populate on the target's information, and so that it can call it at the appropriate time. The name is the only information it needs to pass this reference back up.

Probably the more correct thing for me to do would be to implement my own `PythonMirroredFunction` type which looks just like `Function`, and exposes its name so that the Python equivalent can be looked up, but this seemed a little simpler... :)

**Comment by damienmg** [comment]
Sorry, bear with me but I still do not understand why python needs the name of the function, or do you mean that you declare X functions for the X python implementation, and just pass it always the same rust implementation that call out to python depending on the name?

Btw, I don't think the more correct thing would be to copy paste the code when we can just add a getter to do what you want :). I just want to add a clear explanation to the commit description when merging that PR :)

**Comment by illicitonion** [comment]
> or do you mean that you declare X functions for the X python implementation, and just pass it always the same rust implementation that call out to python depending on the name?

Yeah, that :) Which works just fine for actual function calls, but means that function references need to be translated into python function references when returning values up from the starlark::eval call.

**Comment by illicitonion** [comment]
I opted for publicing up `name` rather than `function_type` because it seemed like a much narrower API to be making forward-compatibility guarantees about, but I'd be happy with either :)

**Comment by damienmg** [comment]
Ok then let's merge this one as this is :)

**Pull request merged**
